sudo: required
dist: trusty
language: node_js
node_js:
  - '6'
install:
  - yarn
before_install:
  # Decrypt the private key
  - openssl aes-256-cbc -K $encrypted_10bf0941d682_key -iv $encrypted_10bf0941d682_iv
    -in .travis/travis_deploy.enc -out travis_deploy -d
  # Set the permission of the key
  - chmod 600 travis_deploy

  # Add the private key to the system
  - cp travis_deploy ~/.ssh/travis_deploy

  # Copy SSH config
  - cp .travis/ssh_config ~/.ssh/config

  # Set Git config
  - git config --global user.name "zgl"
  - git config --global user.email zgl2007dj@gmail.com

  # add jdk8 deps
  - sudo apt-get update
  - sudo apt-get install oracle-java8-installer
  - sudo update-java-alternatives -s java-8-oracle

  # e2e base on phantomjs , try pre deps
  - phantomjs --version
script:
  - npm test
cache:
  yarn: true
after_success:
  #start the ssh agent
  - eval "$(ssh-agent -s)"
  # this key should have push access, set github relative-project deploy with writeable
  - ssh-add ~/.ssh/travis_deploy
  - git remote add deploy git@github.com:zgl2007dj/mk-way.git
  - git push deploy master
  - ssh zouguoliang@130.211.247.128
  - pwd
  - ls -al
branches:
  only:
    - master
