sudo: required
dist: trusty
language: node_js
node_js:
- '6'
install:
- yarn
before_install:
- openssl aes-256-cbc -K $encrypted_10bf0941d682_key -iv $encrypted_10bf0941d682_iv
  -in travis_deploy.enc -out travis_deploy -d
- sudo apt-get update
- sudo apt-get install oracle-java8-installer
- sudo update-java-alternatives -s java-8-oracle
- phantomjs --version
script:
- npm test
- npm run build
cache:
  yarn: true
env:
  global:
  - FTP_USER=user
  - FTP_PASSWORD=password
after_success:
- ls dist
branches:
  only:
  - master
