sudo: required

language: node_js

node_js:
  - "6"

install:
  - yarn

before_script:
  - sudo apt-get update
  - sudo apt-get install oracle-java8-installer
  - sudo update-java-alternatives -s java-8-oracle

script: npm test

cache:
  yarn: true
