sudo: required
language: java

jdk:
  - oraclejdk8

env:
  - NODE_VERSION= 6.10.0

install:
  - nvm install $NODE_VERSION
  - yarn

script:
  - nvm use $NODE_VERSION
  - npm test

cache:
  yarn: true
