sudo: required
language: node_js
jdk: oraclejdk8
node_js:
  - "6"
install:
  - yarn
before_script:
  - apt-get update
  - apt-get install oracle-java8-installer
  - update-java-alternatives -s java-8-oracle
script: npm test
cache: false
