sudo: required

language: node_js

node_js:
  - "6"

install:
  - yarn

addons:
  chrome: stable

before_install:
  - sudo apt-get update
  - sudo apt-get install oracle-java8-installer
  - sudo update-java-alternatives -s java-8-oracle

  - phantomjs --version
  # https://docs.travis-ci.com/user/gui-and-headless-browsers/
  # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: npm test

dist: trusty

cache:
  yarn: true
